name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Update to Node.js 16
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jhonnathan93/plantshop:latest
    - name: Docker Push
      run: docker push jhonnathan93/plantshop
